name: DataMiner CICD Automation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - main
      - master
    tags:
      - "[0-9]+.[0-9]+.[0-9]+.[0-9]+"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  CI:
    uses: SkylineCommunications/_ReusableWorkflows/.github/workflows/Automation Master Workflow.yml@main
    with:
      referenceName: ${{ github.ref_name }}
      runNumber: ${{ github.run_number }}
      referenceType: ${{ github.ref_type }}
      repository: ${{ github.repository }}
      owner: ${{ github.repository_owner }}
      sonarCloudProjectName: SkylineCommunications_SLC-AS-Enable-Disable-ScheduledTasks
      # The API-key: generated in the DCP Admin app (https://admin.dataminer.services/) as authentication for a certain DataMiner System.
    secrets:
      api-key: ${{ secrets.MY_VKD_KEY }}
      sonarCloudToken: ${{ secrets.SONAR_TOKEN }}
    
  # Optional 0 or More CD Jobs as needed
  build:
     if: github.ref_type == 'tag'
     environment: production
     name: CD
     runs-on: ubuntu-latest
     needs: CI

     steps:
       - uses: actions/checkout@v3

       - name: Skyline DataMiner Deploy Action
         uses: SkylineCommunications/Skyline-DataMiner-Deploy-Action@v1
         with:
            # The API-key generated in the DCP Admin app as authentication for a certain DataMiner System, saved in a GitHub secret
            api-key: ${{ secrets.MY_VDK_KEY }}
            # The path to the .sln file of the solution. Atm only DataMiner Automation Script solutions are supported. E.g ./Example/Script.sln. Required for stages: All and Upload.
            solution-path: AutomationScript.sln # optional
            # The chosen name of the artifact. E.g. MyPackageName.  Required for stages: All, Upload and Deploy.
            artifact-name: EnableDisable-ScheduledTasks # Optional
            # The version number for the artifact. Only required for a release run. (format A.B.C). E.g. 1.0.1. Required for stages Upload and All if no build number was provided instead.
            version: 1.0.0 # optional
           



