
  on: [push]

  jobs:
    build:
      name: build
      runs-on: ubuntu-latest
      outputs:
        ARTIFACT_ID: ${{ steps.Build_and_upload_artifact_step.outputs.ARTIFACT_ID }}
      steps:
        - name: Checkout	
          uses: actions/checkout@v3
        - name: Set up NuGet
          uses: nuget/setup-nuget@v1.1.1      
        - name: NuGet restore solution
          run: nuget restore "Enable-Disable-CorrelationRules/AutomationScript.sln" -OutputDirectory ${{ github.workspace }}/packages
        - name: Deploy the artifact on the DataMiner System step
          uses: SkylineCommunications/Skyline-DataMiner-Deploy-Action@v1
          id: Build_and_upload_artifact_step
          with:
            api-key: ${{ secrets.MY_VKD_KEY }}
            solution-path: './Example/Script.sln'
            artifact-name: 'MyArtifactName'
            version: '1.0.1'
            stage: Upload

    deploy:
      name: deploy
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Deploy
          uses: SkylineCommunications/Skyline-DataMiner-Deploy-Action@v1
          with:
            api-key: ${{ secrets.NAME_OF_YOUR_APIKEY_SECRET }}
            stage: Deploy
            timeout: '300'
            artifact-id: ${{ needs.build.outputs.ARTIFACT_ID }}


